In [1]:
import os
import datetime
import pandas as pd
import sqlite3

# 일별 좌석점유율(James)

In [6]:
# 일별 좌석점유율 http://www.kobis.or.kr/kobis/business/stat/boxs/findDailySeatTicketList.do
    
NAME = 'findDailySeatTicketList'
URL = f'http://www.kobis.or.kr/kobis/business/stat/boxs/{NAME}.do'

date = datetime.date(2015, 1, 1)

# while date < datetime.date(2015, 1, 15): # 테스트용
while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1&searchType=2"' \
              f' > 일별좌석점유율-{start_date}.html')
    date += datetime.timedelta(days=7)

2015-01-01 ~ 2015-01-07
2015-01-08 ~ 2015-01-14

In [18]:
df = pd.DataFrame()

date = datetime.date(2015, 1, 1)

# while date < datetime.date(2015, 1, 15): # 테스트용
while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()

    seat = pd.read_html(f'일별좌석점유율-{start_date}.html', encoding='utf-8')

    for i in range(1,8)[::-1]:
         df2 = seat[i][:-1]
         df = pd.concat([df, df2])
        
    date += datetime.timedelta(days=7)

In [20]:
connection = sqlite3.connect('seat.db')
df.to_sql('seat_daily_propotion', connection, index=False
#           , if_exists='replace' # 같은 db 에 덮어쓰는 코드
         )
pd.read_sql('select * from seat_daily_propotion', connection)

# 일별 상영점유율(William)

In [2]:
# 일별 상영점유율 http://www.kobis.or.kr/kobis/business/stat/boxs/findDailyShowTicketList.do

NAME = 'findDailyShowTicketList'
URL = f'http://www.kobis.or.kr/kobis/business/stat/boxs/{NAME}.do'

date = datetime.date(2015, 1, 1)

# while date < datetime.date(2015, 1, 15): # 테스트용
while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1"' \
              f' > 일별상영점유율-{start_date}.html')
    date += datetime.timedelta(days=7)

2015-01-01 ~ 2015-01-07
2015-01-08 ~ 2015-01-14
2015-01-15 ~ 2015-01-21
2015-01-22 ~ 2015-01-28
2015-01-29 ~ 2015-02-04
2015-02-05 ~ 2015-02-11
2015-02-12 ~ 2015-02-18
2015-02-19 ~ 2015-02-25
2015-02-26 ~ 2015-03-04
2015-03-05 ~ 2015-03-11
2015-03-12 ~ 2015-03-18
2015-03-19 ~ 2015-03-25
2015-03-26 ~ 2015-04-01
2015-04-02 ~ 2015-04-08
2015-04-09 ~ 2015-04-15
2015-04-16 ~ 2015-04-22
2015-04-23 ~ 2015-04-29
2015-04-30 ~ 2015-05-06
2015-05-07 ~ 2015-05-13
2015-05-14 ~ 2015-05-20
2015-05-21 ~ 2015-05-27
2015-05-28 ~ 2015-06-03
2015-06-04 ~ 2015-06-10
2015-06-11 ~ 2015-06-17
2015-06-18 ~ 2015-06-24
2015-06-25 ~ 2015-07-01
2015-07-02 ~ 2015-07-08
2015-07-09 ~ 2015-07-15
2015-07-16 ~ 2015-07-22
2015-07-23 ~ 2015-07-29
2015-07-30 ~ 2015-08-05
2015-08-06 ~ 2015-08-12
2015-08-13 ~ 2015-08-19
2015-08-20 ~ 2015-08-26
2015-08-27 ~ 2015-09-02
2015-09-03 ~ 2015-09-09
2015-09-10 ~ 2015-09-16
2015-09-17 ~ 2015-09-23
2015-09-24 ~ 2015-09-30
2015-10-01 ~ 2015-10-07
2015-10-08 ~ 2015-10-14
2015-10-15 ~ 2015-10-21
2015-10-22 ~ 2015-10-28
2015-10-29 ~ 2015-11-04
2015-11-05 ~ 2015-11-11
2015-11-12 ~ 2015-11-18
2015-11-19 ~ 2015-11-25
2015-11-26 ~ 2015-12-02
2015-12-03 ~ 2015-12-09
2015-12-10 ~ 2015-12-16
2015-12-17 ~ 2015-12-23
2015-12-24 ~ 2015-12-30
2015-12-31 ~ 2016-01-06
2016-01-07 ~ 2016-01-13
2016-01-14 ~ 2016-01-20
2016-01-21 ~ 2016-01-27
2016-01-28 ~ 2016-02-03
2016-02-04 ~ 2016-02-10
2016-02-11 ~ 2016-02-17
2016-02-18 ~ 2016-02-24
2016-02-25 ~ 2016-03-02
2016-03-03 ~ 2016-03-09
2016-03-10 ~ 2016-03-16
2016-03-17 ~ 2016-03-23
2016-03-24 ~ 2016-03-30
2016-03-31 ~ 2016-04-06
2016-04-07 ~ 2016-04-13
2016-04-14 ~ 2016-04-20
2016-04-21 ~ 2016-04-27
2016-04-28 ~ 2016-05-04
2016-05-05 ~ 2016-05-11
2016-05-12 ~ 2016-05-18
2016-05-19 ~ 2016-05-25
2016-05-26 ~ 2016-06-01
2016-06-02 ~ 2016-06-08
2016-06-09 ~ 2016-06-15
2016-06-16 ~ 2016-06-22
2016-06-23 ~ 2016-06-29
2016-06-30 ~ 2016-07-06
2016-07-07 ~ 2016-07-13
2016-07-14 ~ 2016-07-20
2016-07-21 ~ 2016-07-27
2016-07-28 ~ 2016-08-03
2016-08-04 ~ 2016-08-10
2016-08-11 ~ 2016-08-17
2016-08-18 ~ 2016-08-24
2016-08-25 ~ 2016-08-31
2016-09-01 ~ 2016-09-07
2016-09-08 ~ 2016-09-14
2016-09-15 ~ 2016-09-21
2016-09-22 ~ 2016-09-28
2016-09-29 ~ 2016-10-05
2016-10-06 ~ 2016-10-12
2016-10-13 ~ 2016-10-19
2016-10-20 ~ 2016-10-26
2016-10-27 ~ 2016-11-02
2016-11-03 ~ 2016-11-09
2016-11-10 ~ 2016-11-16
2016-11-17 ~ 2016-11-23
2016-11-24 ~ 2016-11-30
2016-12-01 ~ 2016-12-07
2016-12-08 ~ 2016-12-14
2016-12-15 ~ 2016-12-21
2016-12-22 ~ 2016-12-28
2016-12-29 ~ 2017-01-04
2017-01-05 ~ 2017-01-11
2017-01-12 ~ 2017-01-18
2017-01-19 ~ 2017-01-25
2017-01-26 ~ 2017-02-01
2017-02-02 ~ 2017-02-08
2017-02-09 ~ 2017-02-15
2017-02-16 ~ 2017-02-22
2017-02-23 ~ 2017-03-01
2017-03-02 ~ 2017-03-08
2017-03-09 ~ 2017-03-15
2017-03-16 ~ 2017-03-22
2017-03-23 ~ 2017-03-29
2017-03-30 ~ 2017-04-05
2017-04-06 ~ 2017-04-12
2017-04-13 ~ 2017-04-19
2017-04-20 ~ 2017-04-26
2017-04-27 ~ 2017-05-03
2017-05-04 ~ 2017-05-10
2017-05-11 ~ 2017-05-17
2017-05-18 ~ 2017-05-24
2017-05-25 ~ 2017-05-31
2017-06-01 ~ 2017-06-07
2017-06-08 ~ 2017-06-14
2017-06-15 ~ 2017-06-21
2017-06-22 ~ 2017-06-28
2017-06-29 ~ 2017-07-05
2017-07-06 ~ 2017-07-12
2017-07-13 ~ 2017-07-19
2017-07-20 ~ 2017-07-26
2017-07-27 ~ 2017-08-02
2017-08-03 ~ 2017-08-09
2017-08-10 ~ 2017-08-16
2017-08-17 ~ 2017-08-23
2017-08-24 ~ 2017-08-30
2017-08-31 ~ 2017-09-06
2017-09-07 ~ 2017-09-13
2017-09-14 ~ 2017-09-20
2017-09-21 ~ 2017-09-27
2017-09-28 ~ 2017-10-04
2017-10-05 ~ 2017-10-11
2017-10-12 ~ 2017-10-18
2017-10-19 ~ 2017-10-25
2017-10-26 ~ 2017-11-01
2017-11-02 ~ 2017-11-08
2017-11-09 ~ 2017-11-15
2017-11-16 ~ 2017-11-22
2017-11-23 ~ 2017-11-29
2017-11-30 ~ 2017-12-06
2017-12-07 ~ 2017-12-13
2017-12-14 ~ 2017-12-20
2017-12-21 ~ 2017-12-27
2017-12-28 ~ 2018-01-03
2018-01-04 ~ 2018-01-10
2018-01-11 ~ 2018-01-17
2018-01-18 ~ 2018-01-24
2018-01-25 ~ 2018-01-31
2018-02-01 ~ 2018-02-07
2018-02-08 ~ 2018-02-14
2018-02-15 ~ 2018-02-21
2018-02-22 ~ 2018-02-28
2018-03-01 ~ 2018-03-07
2018-03-08 ~ 2018-03-14
2018-03-15 ~ 2018-03-21
2018-03-22 ~ 2018-03-28
2018-03-29 ~ 2018-04-04
2018-04-05 ~ 2018-04-11
2018-04-12 ~ 2018-04-18
2018-04-19 ~ 2018-04-25
2018-04-26 ~ 2018-05-02
2018-05-03 ~ 2018-05-09
2018-05-10 ~ 2018-05-16
2018-05-17 ~ 2018-05-23
2018-05-24 ~ 2018-05-30
2018-05-31 ~ 2018-06-06
2018-06-07 ~ 2018-06-13
2018-06-14 ~ 2018-06-20
2018-06-21 ~ 2018-06-27
2018-06-28 ~ 2018-07-04
2018-07-05 ~ 2018-07-11
2018-07-12 ~ 2018-07-18
2018-07-19 ~ 2018-07-25
2018-07-26 ~ 2018-08-01
2018-08-02 ~ 2018-08-08
2018-08-09 ~ 2018-08-15
2018-08-16 ~ 2018-08-22
2018-08-23 ~ 2018-08-29
2018-08-30 ~ 2018-09-05
2018-09-06 ~ 2018-09-12
2018-09-13 ~ 2018-09-19
2018-09-20 ~ 2018-09-26
2018-09-27 ~ 2018-10-03
2018-10-04 ~ 2018-10-10
2018-10-11 ~ 2018-10-17
2018-10-18 ~ 2018-10-24
2018-10-25 ~ 2018-10-31
2018-11-01 ~ 2018-11-07
2018-11-08 ~ 2018-11-14
2018-11-15 ~ 2018-11-21
2018-11-22 ~ 2018-11-28
2018-11-29 ~ 2018-12-05
2018-12-06 ~ 2018-12-12
2018-12-13 ~ 2018-12-19
2018-12-20 ~ 2018-12-26
2018-12-27 ~ 2019-01-02
2019-01-03 ~ 2019-01-09
2019-01-10 ~ 2019-01-16
2019-01-17 ~ 2019-01-23
2019-01-24 ~ 2019-01-30
2019-01-31 ~ 2019-02-06
2019-02-07 ~ 2019-02-13
2019-02-14 ~ 2019-02-20
2019-02-21 ~ 2019-02-27
2019-02-28 ~ 2019-03-06
2019-03-07 ~ 2019-03-13
2019-03-14 ~ 2019-03-20
2019-03-21 ~ 2019-03-27
2019-03-28 ~ 2019-04-03
2019-04-04 ~ 2019-04-10
2019-04-11 ~ 2019-04-17
2019-04-18 ~ 2019-04-24
2019-04-25 ~ 2019-05-01
2019-05-02 ~ 2019-05-08
2019-05-09 ~ 2019-05-15
2019-05-16 ~ 2019-05-22
2019-05-23 ~ 2019-05-29
2019-05-30 ~ 2019-06-05
2019-06-06 ~ 2019-06-12
2019-06-13 ~ 2019-06-19
2019-06-20 ~ 2019-06-26
2019-06-27 ~ 2019-07-03
2019-07-04 ~ 2019-07-10
2019-07-11 ~ 2019-07-17
2019-07-18 ~ 2019-07-24
2019-07-25 ~ 2019-07-31
2019-08-01 ~ 2019-08-07
2019-08-08 ~ 2019-08-14
2019-08-15 ~ 2019-08-21
2019-08-22 ~ 2019-08-28
2019-08-29 ~ 2019-09-04
2019-09-05 ~ 2019-09-11
2019-09-12 ~ 2019-09-18
2019-09-19 ~ 2019-09-25
2019-09-26 ~ 2019-10-02
2019-10-03 ~ 2019-10-09
2019-10-10 ~ 2019-10-16
2019-10-17 ~ 2019-10-23
2019-10-24 ~ 2019-10-30
2019-10-31 ~ 2019-11-06

In [3]:
df = pd.DataFrame()

date = datetime.date(2015, 1, 1)

# while date < datetime.date(2015, 1, 15): # 테스트용
while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()

    seat = pd.read_html(f'일별상영점유율-{start_date}.html', encoding='utf-8')

    for i in range(1,8)[::-1]:
         df2 = seat[i][:-1]
         df = pd.concat([df, df2])
        
    date += datetime.timedelta(days=7)

In [4]:
connection = sqlite3.connect('show.db')
df.to_sql('show_daily_propotion', connection, index=False
#           , if_exists='replace' # 같은 db 에 덮어쓰는 코드
         )
pd.read_sql('select * from show_daily_propotion', connection)

,순위,영화명,개봉일,상영횟수,상영점유율,매출액,누적매출액,관객수,누적관객수
0,1,국제시장,2014-12-17,4650,45.651%,6129982500,47219550096,751754,6097431
1,2,"님아, 그 강을 건너지 마오",2014-11-27,1979,19.429%,1479015600,31324845079,178941,4025319
2,3,기술자들,2014-12-24,1886,18.516%,1299883700,14952363848,160371,1938454
3,4,개를 훔치는 완벽한 방법,2014-12-31,650,6.381%,299346400,608002300,37741,80633
4,5,상의원,2014-12-24,491,4.82%,230484800,5524209364,28439,705071
5,6,더 테너 리리코 스핀토,2014-12-31,367,3.603%,69620500,200984700,8446,26316
6,7,뽀로로 극장판 눈요정 마을 대모험,None,83,0.815%,27846600,1188395900,5561,237436
7,8,쿼바디스,2014-12-10,19,0.187%,4046900,117029800,509,15399
8,9,그 사람 그 사랑 그 세상,2014-11-20,14,0.137%,9467000,162552500,1202,22070
9,10,목숨,2014-12-04,10,0.098%,1399500,275635600,179,35844
10,11,"제자, 옥한흠",2014-10-30,5,0.049%,687000,356418200,87,48547
11,12,파티51,2014-12-11,4,0.039%,225000,13434800,34,1804
12,12,장군의 아들,1990-06-09,4,0.039%,416000,1446000,208,723
13,12,다이빙벨,2014-10-23,4,0.039%,627000,336231500,79,48571
14,12,카트,2014-11-13,4,0.039%,1720800,5914397433,198,812688
15,16,민우씨 오는 날,None,3,0.029%,87000,3415500,17,695
16,17,빅매치,2014-11-27,2,0.02%,0,8952096578,0,1177438
17,17,두 번째 엄마,2014-12-31,2,0.02%,32000,552000,4,153
18,17,거인,2014-11-13,2,0.02%,156000,175489400,23,23176
19,20,앙상블,2014-12-18,1,0.01%,140000,6045500,16,778
20,20,GROW: 인피니트의 리얼 청춘 라이프,2014-12-04,1,0.01%,54000,189463200,9,23874
21,20,명기,2014-12-30,1,0.01%,9000,647000,1,242
22,20,한여름의 판타지아,2015-06-11,1,0.01%,374600,996100,48,148
23,20,숫호구,2014-08-07,1,0.01%,14000,16270000,2,2105
24,20,자유의 언덕,2014-09-04,1,0.01%,207000,309165827,23,38101
25,20,카토 프로젝트,2014-04-17,1,0.01%,2000,1886000,1,619
26,1,국제시장,2014-12-17,4568,45.621%,3782877729,51002427825,470690,6568121
27,2,"님아, 그 강을 건너지 마오",2014-11-27,1930,19.275%,809774300,32134619379,100585,4125904
28,3,기술자들,2014-12-24,1860,18.576%,758620771,15710984619,95119,2033573
29,4,개를 훔치는 완벽한 방법,2014-12-31,645,6.442%,177849329,785851629,23074,103707
...,...,...,...,...,...,...,...,...,...
58784,8,신의 한 수: 귀수편,2019-11-07,15,0.226%,29053000,142282000,3117,18413
58785,9,메기,2019-09-26,14,0.211%,654480,312694777,92,37052
58786,10,두번할까요,2019-10-17,13,0.196%,377000,1437757120,52,173613
58787,11,"오늘, 우리",2019-10-31,10,0.15%,126000,4079500,18,520
58788,12,열두 번째 용의자,2019-10-10,7,0.105%,63000,41697280,11,5420
58789,12,버티고,2019-10-16,7,0.105%,486000,121229840,54,14301
58790,14,극장판 헬로카봇 : 달나라를 구해줘!,2019-09-04,6,0.09%,90000,4576556370,12,589938
58791,15,빨간 마후라,None,5,0.075%,204000,17325000,102,8482
58792,15,북간도의 십자가,2019-10-17,5,0.075%,329500,48466380,44,6162
58793,17,아워 바디,2019-09-26,4,0.06%,636000,74231487,102,8972
58794,17,장사리 : 잊혀진 영웅들,2019-09-25,4,0.06%,1222000,8951959050,244,1132302
58795,19,판소리 복서,2019-10-09,3,0.045%,31000,201731680,5,26646
58796,19,수퍼 디스코,2019-11-28,3,0.045%,5208000,5802000,651,717
58797,19,어제 일은 모두 괜찮아,2019-11-21,3,0.045%,6434000,6434000,714,714
58798,22,아 백범 김구선생,None,2,0.03%,22000,3482000,11,1750
58799,22,아직 지나지 않은 여름,2019-11-01,2,0.03%,6000,43000,3,14
58800,22,나의 노래는 멀리멀리,2019-10-03,2,0.03%,35000,33731180,5,4144
58801,22,사선의 끝,2019-10-30,2,0.03%,15000,258600,3,49
58802,22,내가 사는 세상,2019-03-07,2,0.03%,6000,11200550,3,1666
58803,22,한강에게,2019-04-04,2,0.03%,11000,19713960,3,2788
58804,28,기생충,2019-05-30,1,0.015%,1302000,85875007245,260,10084225
58805,28,교회오빠,2019-05-16,1,0.015%,10000,870816710,1,109381
58806,28,영하의 바람,2019-11-14,1,0.015%,2295000,6692000,255,764
58807,28,나의 특별한 형제,2019-05-01,1,0.015%,600000,12077742074,120,1477627
58808,28,증인,2019-02-13,1,0.015%,700000,20478826331,104,2534331
58809,28,나쁜 녀석들: 더 무비,2019-09-11,1,0.015%,6000,39552792124,1,4573112
58810,28,1919유관순-그녀들의조국,None,1,0.015%,2000,52000,1,26
58811,28,이어도,None,1,0.015%,0,3763500,0,799
58812,28,뽀로로 극장판 보물섬 대모험,2019-04-25,1,0.015%,79000,5886383900,79,766843
58813,28,로망,2019-04-03,1,0.015%,750000,591424900,150,80079

# 일별 스크린점유율(Frank)

In [36]:
# 일별 스크린점유율 http://www.kobis.or.kr/kobis/business/stat/boxs/findDailyScreenTicketList.do
NAME = 'findDailyScreenTicketList'
URL = f'http://www.kobis.or.kr/kobis/business/stat/boxs/{NAME}.do'

date = datetime.date(2015, 1, 1)

while date < datetime.date(2015, 1, 15): # 테스트용
# while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1"' \
              f' > 일별스크린점유율-{start_date}.html')
    date += datetime.timedelta(days=7)

2015-01-01 ~ 2015-01-07
2015-01-08 ~ 2015-01-14

In [37]:
df = pd.DataFrame()

date = datetime.date(2015, 1, 1)

while date < datetime.date(2015, 1, 15): # 테스트용
# while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()

    seat = pd.read_html(f'일별스크린점유율-{start_date}.html', encoding='utf-8')

    for i in range(1,8)[::-1]:
         df2 = seat[i][:-1]
         df = pd.concat([df, df2])
        
    date += datetime.timedelta(days=7)

In [40]:
connection = sqlite3.connect('screen.db')
df.to_sql('show_daily_propotion', connection, index=False
#           , if_exists='replace' # 같은 db 에 덮어쓰는 코드
         )
pd.read_sql('select * from show_daily_propotion', connection)

,순위,영화명,개봉일,스크린수,스크린점유율,매출액,누적매출액,관객수,누적관객수
0,1,국제시장,2014-12-17,941,35.8%,6129982500,47219550096,751754,6097431
1,2,"님아, 그 강을 건너지 마오",2014-11-27,473,18.0%,1479015600,31324845079,178941,4025319
2,3,기술자들,2014-12-24,464,17.7%,1299883700,14952363848,160371,1938454
3,4,상의원,2014-12-24,258,9.8%,230484800,5524209364,28439,705071
4,5,개를 훔치는 완벽한 방법,2014-12-31,196,7.5%,299346400,608002300,37741,80633
5,6,더 테너 리리코 스핀토,2014-12-31,169,6.4%,69620500,200984700,8446,26316
6,7,뽀로로 극장판 눈요정 마을 대모험,None,66,2.5%,27846600,1188395900,5561,237436
7,8,쿼바디스,2014-12-10,12,0.5%,4046900,117029800,509,15399
8,9,목숨,2014-12-04,10,0.4%,1399500,275635600,179,35844
9,10,그 사람 그 사랑 그 세상,2014-11-20,7,0.3%,9467000,162552500,1202,22070
10,11,파티51,2014-12-11,4,0.2%,225000,13434800,34,1804
11,11,다이빙벨,2014-10-23,4,0.2%,627000,336231500,79,48571
12,13,카트,2014-11-13,3,0.1%,1720800,5914397433,198,812688
13,13,민우씨 오는 날,None,3,0.1%,87000,3415500,17,695
14,13,"제자, 옥한흠",2014-10-30,3,0.1%,687000,356418200,87,48547
15,16,빅매치,2014-11-27,2,0.1%,0,8952096578,0,1177438
16,16,거인,2014-11-13,2,0.1%,156000,175489400,23,23176
17,16,두 번째 엄마,2014-12-31,2,0.1%,32000,552000,4,153
18,19,명기,2014-12-30,1,0.0%,9000,647000,1,242
19,19,GROW: 인피니트의 리얼 청춘 라이프,2014-12-04,1,0.0%,54000,189463200,9,23874
20,19,장군의 아들,1990-06-09,1,0.0%,416000,1446000,208,723
21,19,앙상블,2014-12-18,1,0.0%,140000,6045500,16,778
22,19,숫호구,2014-08-07,1,0.0%,14000,16270000,2,2105
23,19,카토 프로젝트,2014-04-17,1,0.0%,2000,1886000,1,619
24,19,자유의 언덕,2014-09-04,1,0.0%,207000,309165827,23,38101
25,19,한여름의 판타지아,2015-06-11,1,0.0%,374600,996100,48,148
26,1,국제시장,2014-12-17,930,35.5%,3782877729,51002427825,470690,6568121
27,2,기술자들,2014-12-24,481,18.4%,758620771,15710984619,95119,2033573
28,3,"님아, 그 강을 건너지 마오",2014-11-27,471,18.0%,809774300,32134619379,100585,4125904
29,4,상의원,2014-12-24,264,10.1%,149272900,5673482264,18455,723526
...,...,...,...,...,...,...,...,...,...
362,2,허삼관,2015-01-14,584,24.9%,551479100,615567100,73635,81503
363,3,오늘의 연애,2015-01-14,577,24.6%,1032903000,1099473000,133838,141522
364,4,"님아, 그 강을 건너지 마오",2014-11-27,264,11.3%,64991300,36580783379,9090,4696415
365,5,기술자들,2014-12-24,146,6.2%,28781000,19736744683,3760,2544717
366,6,워킹걸,2015-01-07,56,2.4%,9121500,1085098979,1186,134144
367,7,개를 훔치는 완벽한 방법,2014-12-31,23,1.0%,9173700,1684918765,1337,221805
368,8,쿼바디스,2014-12-10,12,0.5%,1364400,141777300,219,18836
369,9,목숨,2014-12-04,8,0.3%,466000,283397600,64,36867
370,9,설해,2015-01-08,8,0.3%,183000,27419500,23,3653
371,11,상의원,2014-12-24,5,0.2%,504000,6198263964,72,789628
372,11,더 테너 리리코 스핀토,2014-12-31,5,0.2%,2859000,375039941,387,48526
373,11,뽀로로 극장판 눈요정 마을 대모험,None,5,0.2%,721000,1269500700,167,254045
374,14,파티51,2014-12-11,4,0.2%,210000,15143800,29,2037
375,15,그 사람 그 사랑 그 세상,2014-11-20,3,0.1%,176000,186986500,27,25215
376,16,고양이 장례식,2015-01-15,2,0.1%,1533000,11512600,175,1420
377,17,춘하추동 로맨스,2014-12-04,1,0.0%,21000,8119800,3,1200
378,17,숫호구,2014-08-07,1,0.0%,22000,16348000,4,2117
379,17,악사들,2014-12-04,1,0.0%,12000,7733200,2,1372
380,17,카토 프로젝트,2014-04-17,1,0.0%,4000,1918000,2,635
381,17,두 번째 엄마,2014-12-31,1,0.0%,14000,1010000,2,239
382,17,"제자, 옥한흠",2014-10-30,1,0.0%,40000,359310200,5,48904
383,17,다이빙벨,2014-10-23,1,0.0%,96000,341616500,12,49300
384,17,카트,2014-11-13,1,0.0%,236000,5924979433,30,813982
385,17,레드 툼,2015-07-09,1,0.0%,35000,1257000,7,230
386,17,순천,2014-09-04,1,0.0%,10000,22832200,5,3610
387,17,족구왕,2014-08-21,1,0.0%,40000,359459000,5,45666
388,17,못,2014-11-20,1,0.0%,10000,16941600,2,2368
389,17,앙상블,2014-12-18,1,0.0%,34000,6939500,6,900
390,17,독립영화발표회(251회) - 박영석 프로그래머 추천전,None,1,0.0%,0,0,0,0
391,17,자유의 언덕,2014-09-04,1,0.0%,48000,310619827,6,38286

# 상영내역(Andy)

In [ ]:
# 상영내역 http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistorySc.do

#http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistoryScXls.do
#?theaCd=001123&theaArea=Y&
#showStartDt=2019-11-19&showEndDt=2019-11-26"

http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistoryScXls.do?theaCd=001123&theaArea=Y&showStartDt=2018-01-01&showEndDt=2018-12-31&choice=2&sTheaNm=CGV%20강남"

URL = f'http://www.kobis.or.kr/kobis/business/mast/thea/findShowHistoryScXls.do'

showStartDt = 2015-01-01
showEndDt = 2019-10-31
sTheaNm = CGV%20강남
    
os.system(f'curl "{URL}?showStartDt={showStartDt}&endDate={showEndDt}&sTheaNm={sTheaNm}"' \
          f' > 일별상영점유율-{start_date}.html')

date = datetime.date(2015, 1, 1)

while date < datetime.date(2019, 11, 1):
    start_date = date.isoformat()
    end_date = (date + datetime.timedelta(days=6)).isoformat()
    print(start_date, '~', end_date)
    os.system(f'curl "{URL}?loadEnd=0&dmlMode=excel&' \
              f'startDate={start_date}&endDate={end_date}&repNationCd=1"' \
              f' > 일별상영점유율-{start_date}.html')
    date += datetime.timedelta(days=7)
    
    heaCd: 002041
theaArea: Y
showStartDt: 2019-11-20
showEndDt: 2019-11-27
sWideareaCd: 
sBasareaCd: 
sTheaCd: 
choice: 2
sTheaNm: CGV  김포한강